name: release
on:
  push:
    branches:
      - main
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@yamcodes/ui"

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    needs: create-release
    if: ${{ needs.create-release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun and NPM registry
        uses: oven-sh/setup-bun@v1
        with:
          registry-url: https://registry.npmjs.org

      - name: Install core dependencies
        run: bun i

      - name: Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
